try{
    console.lo(hi);
}catch(err){
    console.log(err)
    console.log(err.name)
    console.log(err.message)
}